services:
  - type: web
    name: savemeaseat_backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    runtime: python
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: https://savemeaseat-backend.onrender.com
