# Generated by Django 5.2.3 on 2025-06-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slides/')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='hero_slides',
        ),
        migrations.AlterField(
            model_name='storyevent',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='story_icons/'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='hero_slides',
            field=models.ManyToManyField(blank=True, to='core.heroslideimage'),
        ),
    ]
