# Generated by Django 5.2.3 on 2025-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslideimage_remove_eventinfo_hero_slides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
