# Generated by Django 5.2.3 on 2025-06-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventinfo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('center_cover_image', models.ImageField(upload_to='event/cover/')),
                ('section_image', models.ImageField(upload_to='event/section/')),
                ('bride_first_name', models.CharField(max_length=100)),
                ('bride_last_name', models.CharField(max_length=100)),
                ('bride_message', models.TextField()),
                ('bride_image', models.ImageField(upload_to='event/bride/')),
                ('groom_first_name', models.CharField(max_length=100)),
                ('groom_last_name', models.CharField(max_length=100)),
                ('groom_message', models.TextField()),
                ('groom_image', models.ImageField(upload_to='event/groom/')),
                ('slider_image_1', models.ImageField(blank=True, null=True, upload_to='event/slider/')),
                ('slider_image_2', models.ImageField(blank=True, null=True, upload_to='event/slider/')),
                ('slider_image_3', models.ImageField(blank=True, null=True, upload_to='event/slider/')),
                ('slider_image_4', models.ImageField(blank=True, null=True, upload_to='event/slider/')),
                ('slider_image_5', models.ImageField(blank=True, null=True, upload_to='event/slider/')),
                ('slider_image_6', models.ImageField(blank=True, null=True, upload_to='event/slider/')),
                ('love_story_first_meet_date', models.CharField(max_length=50)),
                ('love_story_first_meet_desc', models.TextField()),
                ('love_story_first_date_date', models.CharField(max_length=50)),
                ('love_story_first_date_desc', models.TextField()),
                ('love_story_proposal_date', models.CharField(max_length=50)),
                ('love_story_proposal_desc', models.TextField()),
                ('love_story_engagement_date', models.CharField(max_length=50)),
                ('love_story_engagement_desc', models.TextField()),
                ('sweet_image_1', models.ImageField(blank=True, null=True, upload_to='event/sweet/')),
                ('sweet_image_2', models.ImageField(blank=True, null=True, upload_to='event/sweet/')),
                ('sweet_image_3', models.ImageField(blank=True, null=True, upload_to='event/sweet/')),
                ('sweet_image_4', models.ImageField(blank=True, null=True, upload_to='event/sweet/')),
                ('sweet_image_5', models.ImageField(blank=True, null=True, upload_to='event/sweet/')),
                ('sweet_image_6', models.ImageField(blank=True, null=True, upload_to='event/sweet/')),
                ('time_card1_title', models.CharField(max_length=100)),
                ('time_card1_text1', models.CharField(max_length=255)),
                ('time_card1_text2', models.CharField(max_length=255)),
                ('time_card1_text3', models.CharField(max_length=255)),
                ('time_card1_text4', models.CharField(max_length=255)),
                ('time_card1_text5', models.CharField(max_length=255)),
                ('time_card1_url', models.URLField()),
                ('time_card2_title', models.CharField(max_length=100)),
                ('time_card2_text1', models.CharField(max_length=255)),
                ('time_card2_text2', models.CharField(max_length=255)),
                ('time_card2_text3', models.CharField(max_length=255)),
                ('time_card2_text4', models.CharField(max_length=255)),
                ('time_card2_text5', models.CharField(max_length=255)),
                ('time_card2_url', models.URLField()),
                ('time_card3_title', models.CharField(max_length=100)),
                ('time_card3_text1', models.CharField(max_length=255)),
                ('time_card3_text2', models.CharField(max_length=255)),
                ('time_card3_text3', models.CharField(max_length=255)),
                ('time_card3_text4', models.CharField(max_length=255)),
                ('time_card3_text5', models.CharField(max_length=255)),
                ('time_card3_url', models.URLField()),
                ('main_map_url', models.URLField()),
                ('gift_1', models.CharField(max_length=255)),
                ('gift_2', models.CharField(max_length=255)),
                ('gift_3', models.CharField(max_length=255)),
                ('gift_4', models.CharField(max_length=255)),
                ('gift_5', models.CharField(max_length=255)),
                ('thank_you_message', models.TextField(default='Thank you for your love and support!')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Couple',
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='hero_slides',
        ),
        migrations.DeleteModel(
            name='EventScheduleItem',
        ),
        migrations.DeleteModel(
            name='FooterContent',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='GiftContribution',
        ),
        migrations.DeleteModel(
            name='RSVPSettings',
        ),
        migrations.DeleteModel(
            name='StoryEvent',
        ),
        migrations.DeleteModel(
            name='EventInfo',
        ),
        migrations.DeleteModel(
            name='HeroSlideImage',
        ),
    ]
