# Generated by Django 5.2.3 on 2025-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='love_story_engagement_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/love_story/'),
        ),
        migrations.AddField(
            model_name='event',
            name='love_story_first_date_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/love_story/'),
        ),
        migrations.AddField(
            model_name='event',
            name='love_story_first_meet_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/love_story/'),
        ),
        migrations.AddField(
            model_name='event',
            name='love_story_proposal_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/love_story/'),
        ),
    ]
