# Generated by Django 5.2.3 on 2025-06-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_event_bride_first_name_alter_event_bride_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_header_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
