# Generated by Django 5.2.3 on 2025-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_additional_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_map_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
