# Generated by Django 5.2.3 on 2025-06-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_event_main_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridesmaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/bridesmaids/')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridesmaids', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Groomsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/groomsmen/')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groomsmen', to='core.event')),
            ],
        ),
    ]
