# Generated by Django 5.2.3 on 2025-06-30 12:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bridesmaid_groomsman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridesmaid',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/bridesmaids/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bride_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/bride/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='center_cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/cover/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/groom/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='love_story_engagement_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/love_story/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='love_story_first_date_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/love_story/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='love_story_first_meet_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/love_story/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='love_story_proposal_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/love_story/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='section_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/section/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slider_image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/slider/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slider_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/slider/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slider_image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/slider/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slider_image_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/slider/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slider_image_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/slider/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slider_image_6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/slider/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sweet_image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/sweet/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sweet_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/sweet/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sweet_image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/sweet/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sweet_image_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/sweet/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sweet_image_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/sweet/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sweet_image_6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/sweet/'),
        ),
        migrations.AlterField(
            model_name='groomsman',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event/groomsmen/'),
        ),
    ]
