# Generated by Django 5.2.3 on 2025-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_programitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
