# Generated by Django 5.2.3 on 2025-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_event_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
