# Generated by Django 5.2.3 on 2025-10-31 20:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_invitations_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_past_event',
            field=models.BooleanField(default=False, help_text='Automatically set to True if event date is in the past'),
        ),
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(help_text='Main wedding title (e.g., "Sophia & Alexander")', max_length=255)),
                ('logo_text', models.CharField(blank=True, help_text='Logo/Initials (e.g., "S & A")', max_length=50, null=True)),
                ('event_date', models.DateTimeField(help_text='Wedding date and time')),
                ('event_location', models.CharField(help_text='City/location name (e.g., "Lusaka, Zambia")', max_length=200)),
                ('primary_color', models.CharField(default='#f8f5f2', help_text='Primary background color (hex format)', max_length=7)),
                ('secondary_color', models.CharField(default='#e8d5c4', help_text='Secondary elements color (hex format)', max_length=7)),
                ('accent_color', models.CharField(default='#c8a97e', help_text='Highlights and accents color (hex format)', max_length=7)),
                ('countdown_title', models.CharField(blank=True, default='Counting Down to Our Special Day', max_length=255, null=True)),
                ('bride_name', models.CharField(help_text='Bride full name', max_length=100)),
                ('bride_image', cloudinary.models.CloudinaryField(help_text='Bride photo upload', max_length=255, verbose_name='wedding/bride/')),
                ('bride_description', models.TextField(blank=True, help_text='Bride description/bio', null=True)),
                ('groom_name', models.CharField(help_text='Groom full name', max_length=100)),
                ('groom_image', cloudinary.models.CloudinaryField(help_text='Groom photo upload', max_length=255, verbose_name='wedding/groom/')),
                ('groom_description', models.TextField(blank=True, help_text='Groom description/bio', null=True)),
                ('story_paragraph1', models.TextField(blank=True, help_text='Opening story paragraph', null=True)),
                ('story_highlight', models.TextField(blank=True, help_text='Special quote or highlight', null=True)),
                ('story_paragraph2', models.TextField(blank=True, help_text='Continuation of story', null=True)),
                ('venue_name', models.CharField(help_text='Name of venue (e.g., "The Glass House")', max_length=255)),
                ('venue_description', models.TextField(blank=True, help_text='Detailed venue description', null=True)),
                ('venue_address', models.TextField(help_text='Full venue address')),
                ('ceremony_time', models.TimeField(help_text='Ceremony start time')),
                ('reception_time', models.TimeField(blank=True, help_text='Reception start time', null=True)),
                ('parking_info', models.TextField(blank=True, help_text='Parking details and instructions', null=True)),
                ('transport_info', models.TextField(blank=True, help_text='Public transport information', null=True)),
                ('map_method', models.CharField(choices=[('search', 'Interactive Search (OpenStreetMap)'), ('google', 'Google Maps Embed')], default='search', help_text='Choose map display method', max_length=20)),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate', max_digits=10, null=True)),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate', max_digits=10, null=True)),
                ('map_place_name', models.CharField(blank=True, help_text='Place name from map search', max_length=255, null=True)),
                ('map_formatted_address', models.TextField(blank=True, help_text='Formatted address from geocoding', null=True)),
                ('google_maps_url', models.URLField(blank=True, help_text='Google Maps embed URL', max_length=1000, null=True)),
                ('dress_code', models.CharField(blank=True, help_text='Dress code (e.g., "Formal Attire", "Black Tie")', max_length=100, null=True)),
                ('dress_code_description', models.TextField(blank=True, help_text='Additional dress code details', null=True)),
                ('accommodation_name', models.CharField(blank=True, help_text='Recommended hotel name', max_length=255, null=True)),
                ('accommodation_address', models.TextField(blank=True, help_text='Hotel address', null=True)),
                ('rsvp_title', models.CharField(blank=True, default='RSVP', max_length=100, null=True)),
                ('rsvp_subtitle', models.CharField(blank=True, help_text='e.g., "Kindly respond by September 1st"', max_length=255, null=True)),
                ('rsvp_background_image', cloudinary.models.CloudinaryField(blank=True, help_text='RSVP section background image', max_length=255, null=True, verbose_name='wedding/rsvp/')),
                ('footer_logo', models.CharField(blank=True, help_text='Footer logo text', max_length=100, null=True)),
                ('footer_text', models.TextField(blank=True, help_text='Footer message text', null=True)),
                ('footer_date_location', models.CharField(blank=True, help_text='Date and location summary for footer', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='Publish wedding website')),
                ('is_past_event', models.BooleanField(default=False, help_text='Automatically set to True if event date is in the past')),
                ('invitations_sent', models.BooleanField(default=False, help_text='Track if invitations have been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(limit_choices_to={'name': 'wedding'}, on_delete=django.db.models.deletion.PROTECT, related_name='wedding_events', to='core.eventtype')),
            ],
            options={
                'verbose_name': 'Wedding Event',
                'verbose_name_plural': 'Wedding Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='WeddingBridesmaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=255)),
                ('role', models.CharField(help_text='Position (e.g., "Maid of Honor", "Bridesmaid")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Relationship description', null=True)),
                ('image', cloudinary.models.CloudinaryField(help_text='Bridesmaid photo upload', max_length=255, verbose_name='wedding/bridesmaids/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridesmaids', to='core.weddingevent')),
            ],
            options={
                'verbose_name': 'Wedding Bridesmaid',
                'verbose_name_plural': 'Wedding Bridesmaids',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeddingGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Gallery image upload', max_length=255, verbose_name='wedding/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Image description for accessibility', max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.weddingevent')),
            ],
            options={
                'verbose_name': 'Wedding Gallery Image',
                'verbose_name_plural': 'Wedding Gallery Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingGroomsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=255)),
                ('role', models.CharField(help_text='Position (e.g., "Best Man", "Groomsman")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Relationship description', null=True)),
                ('image', cloudinary.models.CloudinaryField(help_text='Groomsman photo upload', max_length=255, verbose_name='wedding/groomsmen/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groomsmen', to='core.weddingevent')),
            ],
            options={
                'verbose_name': 'Wedding Groomsman',
                'verbose_name_plural': 'Wedding Groomsmen',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeddingRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('attending', models.CharField(choices=[('yes', 'Yes, I will attend'), ('no', 'No, I cannot attend'), ('maybe', 'Maybe')], max_length=10)),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Special message or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='core.weddingevent')),
            ],
            options={
                'verbose_name': 'Wedding RSVP',
                'verbose_name_plural': 'Wedding RSVPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Slide image upload', max_length=255, verbose_name='wedding/slider/')),
                ('title', models.CharField(help_text='Main heading for slide', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Secondary text', max_length=255, null=True)),
                ('date_text', models.CharField(blank=True, help_text='Date/location text for slide', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='core.weddingevent')),
            ],
            options={
                'verbose_name': 'Wedding Slider Image',
                'verbose_name_plural': 'Wedding Slider Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
