# Generated by Django 5.2.3 on 2025-12-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_eventtype_event_is_past_event_weddingevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingevent',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='venue_description',
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='ceremony_date',
            field=models.DateField(blank=True, help_text='Ceremony date', null=True),
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='ceremony_venue_address',
            field=models.TextField(blank=True, help_text='Ceremony venue full address', null=True),
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='ceremony_venue_description',
            field=models.TextField(blank=True, help_text='Ceremony venue description', null=True),
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='ceremony_venue_name',
            field=models.CharField(blank=True, help_text='Ceremony venue name (e.g., "St. Michael\'s Church")', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Reception date', null=True),
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='reception_venue_address',
            field=models.TextField(blank=True, help_text='Reception venue full address', null=True),
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='reception_venue_description',
            field=models.TextField(blank=True, help_text='Reception venue description', null=True),
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='reception_venue_name',
            field=models.CharField(blank=True, help_text='Reception venue name (e.g., "The Glass House")', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingevent',
            name='ceremony_time',
            field=models.TimeField(blank=True, help_text='Ceremony start time', null=True),
        ),
        migrations.CreateModel(
            name='WeddingGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', models.CharField(choices=[('money', 'Money Transfer'), ('bank', 'Bank Transfer'), ('registry', 'Registry'), ('other', 'Other')], default='money', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='Provider name e.g., Airtel Money', max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, help_text='Account or recipient name', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Phone number / account number', max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Any instructions for the contribution', null=True)),
                ('url', models.URLField(blank=True, help_text='Optional link (e.g., registry link)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='core.weddingevent')),
            ],
            options={
                'verbose_name': 'Wedding Gift',
                'verbose_name_plural': 'Wedding Gifts',
                'ordering': ['order', 'id'],
            },
        ),
    ]
